#!/usr/bin/env python
# coding: utf-8

import numpy as np
from random import sample, seed
import time

# Auxiliary function to build hypergraph
def duplicates(x):
    '''
    Return True if list x has repeated elements
    '''
    return any(x.count(element) > 1 for element in x)

# Auxiliary function to build hypergraph
def repeated_group(x, X):
    '''
    Return True if x is a list contained in X,
    where X is a list of lists
    '''
    for y in X:
        if set(y) == set(x):
            return True
    return False

# Search for a regular hypergraph candidate 
def regular_hypergraph_try(N, k, q):
    '''
    Sample from list L of indices sub-groups of exactly q indices.
    Two comditions:
        a) each group does not include repeated indices
        b) there are no repeated groups
    If the two conditions are satisfied, put indices from L into first list in x_try
    '''
    # L is a list including each fermionic indices kq times
    L = list(np.array([[i]*int(k*q) for i in range(N)]).flatten())
    
    x_try = [[], L]
    
    for j in range(int(k*q*N)):
        if (len(L) >= q):
            x_test =  sample(L, q)
            if duplicates(x_test) == False and repeated_group(x_test, x_try[0]) == False:
                for i in x_test:
                    L.remove(i)
                x_try[0].append(x_test)
        
    return x_try

# Run regular_hypergraph_try until L is empty to obtain a regular hypergraph
def regular_hypergraph(N, k, q, random_seed):
    seed(random_seed)
    x_try = regular_hypergraph_try(N, k, q)
    while x_try[1] != []:
        x_try = regular_hypergraph_try(N, k, q)
    h = np.sort(x_try[0])
    return tuple(map(tuple, h)) 

# Load hypergraph from text file generated by hyper-save.ipynb
def load_hypergraph(N, k, q, s):
    filename = r'../hypergraph/data/N{}-q{}-k{}-s{}.txt'.format(N, q, k, s)
    hyperedges_array = np.loadtxt(filename)
    return tuple(map(tuple, hyperedges_array.astype('int')))

# Auxiliary function to measue running time
def convert(seconds): 
    seconds = seconds % (24*3600) 
    hour = seconds//3600
    seconds %= 3600
    minutes = seconds//60
    seconds %= 60
      
    return '%dh:%02dmin:%02ds' % (hour, minutes, seconds) 


